# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: XJTU Wiki
contact: https://github.com/xjtu-wiki/xjtu-wiki.github.io/issues
description: >- # this means to ignore newlines until "baseurl:"
  Because people can get things done in a much better and more efficient way with the power of organized information. 
  XJTU Wiki provides useful information for international students visiting Xi'an Jiaotong University. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xjtu-wiki.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: N/A
github_username:  xjtu-wiki

# Build settings
markdown: kramdown
kramdown: 
  input: GFM
  auto_ids: true  # Auto-generate ID's for headings

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections: 
  guidelines:
    output: true
    permalink: /:collection/:path/  # Add this line so that the collection links work on Gitlab. 
  locations: 
    output: true
    permalink: /:collection/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
